import express from "express";
import { getUsers, Login, Logout, Register } from "../controller/Users.js";
import { verifyToken } from "../middleware/VeriftyToken.js";
import { RefreshToken } from "../controller/RefreshToken.js";
const router = express.Router();
router.get("/users", verifyToken, getUsers);
router.post("/users", Register);
router.post("/login", Login);
router.get("/token", RefreshToken);
router.delete("/logout", Logout);
export default router;
